[package]
name = "wasmer-examples/nuxt-wasmer-starter"
version = "0.2.0"
description = "Nuxt static website Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/nuxt-wasmer-starter"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = ".output/public"
